tap "dracula/install"
tap "Homebrew/bundle"

cask "lulu"

brew "trash"
brew "wget"
brew "yarn"
brew "zsh"
brew "grep"
brew "screen"
brew "tree"
brew "zsh-autosuggestions"

cask "appcleaner"
cask "brave-browser"
cask "dracula-terminal"
cask "fantastical"
cask "hiddenbar"
cask "iterm2"
cask "keyclu"
cask "logi-options-plus"
cask "notion"
cask "onyx"
cask "rectangle"
cask "shottr"
cask "slack"
cask "todoist"
cask "visual-studio-code"
cask "zoom"
vscode "batisteo.vscode-django"
vscode "bibhasdn.django-snippets"
vscode "ecmel.vscode-html-css"
vscode "esbenp.prettier-vscode"
vscode "GitHub.vscode-pull-request-github"
vscode "ms-python.python"
vscode "xabikos.JavaScriptSnippets"
