tap "dracula/install"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"

cask "lulu"

brew "trash"
brew "bat"
brew "mas"
brew "wget"
brew "yarn"
brew "zsh"
brew "grep"
brew "screen"
brew "tree"
brew "zsh-autosuggestions"
brew "git"
brew "git-lfs"
brew "git-flow"
brew "git-extras"
brew "git-delta"
brew "lazygit"
brew "tidy-viewer"
brew "font-roboto-mono-nerd-font"

cask "appcleaner"
cask "brave-browser"
cask "dracula-terminal"
cask "fantastical"
cask "hiddenbar"
cask "iterm2"
cask "keyclu"
cask "logi-options-plus"
cask "notion"
cask "onyx"
cask "rectangle"
cask "shottr"
cask "slack"
cask "todoist"
cask "visual-studio-code"
cask "zoom"

